In [5]:
import torch
print(torch.version)

<module 'torch.version' from 'd:\\d drive\\AN\\envs\\gpu_env\\lib\\site-packages\\torch\\version.py'>


In [7]:
if torch.cuda.is_available():
    print("GPU is avaliable")
    print(f"using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is avaliable
using GPU: NVIDIA GeForce RTX 4050 Laptop GPU


# Create Tensor

In [8]:
# using empty 
torch.empty(2,3)

tensor([[7.0407e+13, 1.1883e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [9]:
x = torch.tensor([[1,2,3],[4,5,6]])
x 

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
x.shape

torch.Size([2, 3])

In [11]:
x.dtype

torch.int64

In [13]:
# addition 
x +2
# sub
x-3
#multiplication
x*3

15

# Matrix

In [13]:
f = torch.randint(size=(2,3),low=0, high=10)
g = torch.randint(size=(3,2),low =0 , high =10)

print(f)
print(g)

tensor([[5, 3, 5],
        [6, 5, 1]])
tensor([[1, 0],
        [7, 5],
        [3, 1]])


In [14]:
# matrix multiplication
torch.matmul(f,g)

tensor([[41, 20],
        [44, 26]])

In [15]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

# dot product
torch.dot(vector1,vector2)

tensor(11)

In [16]:
torch.transpose(f,0,1)

tensor([[5, 6],
        [3, 5],
        [5, 1]])

# Comparison operations

In [31]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10 , dtype =torch.float32)

print(i)
print(j)

tensor([[7, 0, 5],
        [7, 5, 0]])
tensor([[4., 6., 1.],
        [4., 4., 5.]])


In [25]:
# greater then 
i > j
#less then
i>j

tensor([[ True, False, False],
        [ True, False, False]])

In [26]:
torch.log(j)

tensor([[  -inf, 2.1972, 1.9459],
        [0.0000, 1.3863, 0.6931]])

In [27]:
torch.exp(j)

tensor([[1.0000e+00, 8.1031e+03, 1.0966e+03],
        [2.7183e+00, 5.4598e+01, 7.3891e+00]])

In [28]:
torch.sqrt(j)

tensor([[0.0000, 3.0000, 2.6458],
        [1.0000, 2.0000, 1.4142]])

In [29]:
torch.sigmoid(j)

tensor([[0.5000, 0.9999, 0.9991],
        [0.7311, 0.9820, 0.8808]])

In [32]:
torch.softmax(j,dim=0)

tensor([[0.5000, 0.8808, 0.0180],
        [0.5000, 0.1192, 0.9820]])

In [33]:
torch.relu(j)

tensor([[4., 6., 1.],
        [4., 4., 5.]])

# Inplace Operation

In [34]:
m = torch.rand(2,3)
n= torch.rand(2,3)

print(m)
print(n)

tensor([[0.3887, 0.8861, 0.5123],
        [0.0633, 0.0813, 0.5882]])
tensor([[0.3359, 0.3192, 0.4295],
        [0.3039, 0.4512, 0.2905]])


In [35]:
m.add_(n)

tensor([[0.7246, 1.2053, 0.9418],
        [0.3673, 0.5325, 0.8787]])

In [36]:
torch.relu(m)

tensor([[0.7246, 1.2053, 0.9418],
        [0.3673, 0.5325, 0.8787]])

# Tensor Operations Gpu

In [37]:
torch.cuda.is_available()

True

In [38]:
device = torch.device('cuda')

In [39]:
torch.rand((2,3),device=device)

tensor([[0.2192, 0.5336, 0.8447],
        [0.8894, 0.0339, 0.2373]], device='cuda:0')